In [1]:
import torch
from scipy.stats import truncnorm

def truncated_normal_(tensor, mean=0, std=0.02):
    size = tensor.shape
    tmp = tensor.new_empty(size + (4,)).normal_()
    valid = (tmp < 2) & (tmp > -2)
    ind = valid.max(-1, keepdim=True)[1]
    tensor.data.copy_(tmp.gather(-1, ind).squeeze(-1))
    tensor.data.mul_(std).add_(mean)
    return tensor


In [34]:
size = 128
tensor = torch.zeros(2,size)
truncated_normal_(tensor)
r = tensor.numpy()
r.shape

(2, 128)

In [49]:
one_hot = torch.nn.functional.one_hot(torch.tensor([0,0,1,0,1,1,1,1,1,1,0,0,0,0,1,1,1,1,1,0,0,0]), num_classes=2)
one_hot

tensor([[1, 0],
        [1, 0],
        [0, 1],
        [1, 0],
        [0, 1],
        [0, 1],
        [0, 1],
        [0, 1],
        [0, 1],
        [0, 1],
        [1, 0],
        [1, 0],
        [1, 0],
        [1, 0],
        [0, 1],
        [0, 1],
        [0, 1],
        [0, 1],
        [0, 1],
        [1, 0],
        [1, 0],
        [1, 0]])

In [50]:
torch.mm(one_hot.float(),tensor)

tensor([[-0.0083,  0.0035, -0.0032,  ..., -0.0003,  0.0088,  0.0049],
        [-0.0083,  0.0035, -0.0032,  ..., -0.0003,  0.0088,  0.0049],
        [-0.0275,  0.0056,  0.0011,  ...,  0.0246, -0.0042, -0.0039],
        ...,
        [-0.0083,  0.0035, -0.0032,  ..., -0.0003,  0.0088,  0.0049],
        [-0.0083,  0.0035, -0.0032,  ..., -0.0003,  0.0088,  0.0049],
        [-0.0083,  0.0035, -0.0032,  ..., -0.0003,  0.0088,  0.0049]])

In [29]:
type(one_hot)

torch.Tensor

In [30]:
type(tensor)

torch.Tensor

In [21]:
one_hot.shape

torch.Size([22, 2])

In [22]:
tensor.shape

torch.Size([2, 128])

In [25]:
mat1 = torch.randn(2, 3)
mat2 = torch.randn(3, 3)
torch.mm(mat1,mat2)

tensor([[ 4.0712, -2.7983,  2.3474],
        [-2.6403,  0.2335, -3.0342]])

In [74]:
import torch.nn as nn
embed_speaker = nn.Embedding(2+1,1024, padding_idx=0)

In [75]:
embed_speaker(torch.LongTensor([[1,1,1,1,2,2,2,1,1,1,1,2,2,2,0,0],[0,0,0,0,1,1,1,1,0,0,0,0,1,1,1,1]]))

tensor([[[-0.7353, -0.7707,  0.3066,  ...,  0.9938, -1.1099, -2.4504],
         [-0.7353, -0.7707,  0.3066,  ...,  0.9938, -1.1099, -2.4504],
         [-0.7353, -0.7707,  0.3066,  ...,  0.9938, -1.1099, -2.4504],
         ...,
         [ 0.2617, -0.1962, -1.2705,  ..., -0.5788,  0.4254, -1.2329],
         [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
         [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000]],

        [[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
         [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
         [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
         ...,
         [-0.7353, -0.7707,  0.3066,  ...,  0.9938, -1.1099, -2.4504],
         [-0.7353, -0.7707,  0.3066,  ...,  0.9938, -1.1099, -2.4504],
         [-0.7353, -0.7707,  0.3066,  ...,  0.9938, -1.1099, -2.4504]]],
       grad_fn=<EmbeddingBackward>)

In [68]:
torch.LongTensor([[3,7,8,12],[5,12,21,27]])

tensor([[ 3,  7,  8, 12],
        [ 5, 12, 21, 27]])

In [66]:
torch.eye(10)[1]


tensor([0., 1., 0., 0., 0., 0., 0., 0., 0., 0.])